version: "3.3"

services:
  my-server:
    build:
      context: ./server
    restart: always
    environment:
      VIRTUAL_HOST: python_flask.lo  # TODO Specfiy domain name.
      # LETSENCRYPT_HOST: todo       # TODO Specfiy domain name.
      # LETSENCRYPT_MAIL: vincent.mader@icloud.com
    ports:
      - 5005:5005  # TODO Specify port.
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_mxyz_proxy_network 
    # ^ This has to be the same name as specified in `./proxy/docker-compose.yml`.
    #   Additionally, it it prefixed by the proxy directory name (see "docker network ls").
