version: "3.3"

services:
  my-server:
    build:
      context: ./
    restart: always
    environment:
      VIRTUAL_HOST: barwuerfeln.de, www.barwuerfeln.de
      LETSENCRYPT_HOST: barwuerfeln.de
      LETSENCRYPT_MAIL: vincent.mader@icloud.com
    ports:
      - 5020:5020
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_mxyz_proxy_network 
    # ^ This has to be the same name as specified in `./proxy/docker-compose.yml`.
    #   Additionally, it it prefixed by the proxy directory name (see "docker network ls").
